version: 2
updates:
  - package-ecosystem: maven
    directory: /Beroepsproduct_2
    schedule:
      interval: weekly
  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: weekly
